import React, { useState } from "react";
import { toast } from "react-hot-toast";
import axios from "axios";

export const Terms = () => {
  const apiUrl = process.env.REACT_APP_API_URL;
  const params = new URLSearchParams(document.location.search);
  const id = params.get("id");

  const [read, setRead] = useState(false);

  const apr = () => {
    axios
      .post(
        apiUrl + "/approve",
        { id: id },
        {
          "Content-Type": "applicatio /json",
        }
      )
      //   .then((a) => setId(a.data))
      .then((a) => {
        toast.success("Thank you for reading the Terms and Conditions");
        setRead(true);
      })
      .catch((err) => console.error(err));
  };

  return (
    <div>
      <div className="header">
        Terms and Conditions &amp; Privacy Policy
      </div>
      <div className="terms">
        <h1 className="terms-titles">Terms and Conditions:</h1>
        <h3 className="terms-titles">Introduction:</h3>
        Welcome to the Mobile Application and the Internet Site
        https://www.massescontent.com/ and its associated services, such as the
        mobile and/or web applications (hereinafter "The Mobile Application and
        the Site") owned by MASSES GLOBAL SAS (together with its affiliated and
        related companies, “MASSES” and/or “MASSES GLOBAL SAS”). The terms and
        conditions described below (hereinafter the "T&amp;Cs") are intended to
        regulate the use made by people who access the Mobile Application and
        the Site.
        <br />
        <br />
        We call "User" of the Mobile Application and the Site any person
        registered or who uses the Mobile Application and the Site. Anyone can
        register or use the Mobile Application and the Site as long as they
        accept the T&amp;Cs, along with all other policies and principles that
        govern The Mobile Application and the Site, such as the "Privacy
        Policies", "Legal Notices", "T&amp;Cs" and "Cookies Policies".
        <br />
        <br />
        MASSES only provides the Mobile Application and the Site to bring
        together both the Offering User of a service (hereinafter "Offering
        Users") and the User interested in contracting such offers (hereinafter
        "User", and as a whole with the Offering Users "Users”).
        <br />
        <br />
        The Offering User may offer on the Platform Audiovisual Content
        Generated by the same (hereinafter the "UGC"), and each User will be
        able to identify the Offering Users when selecting the UGC that is of
        interest, since when previously selecting a UGC it is indicated that it
        is sold and delivered by the selected Offering User.
        <br />
        <br />
        MASSES only makes available to all its Users, through the Mobile
        Application and the Site, a virtual linking space, it being a mere
        technical intermediary between the Parties (hereinafter the "Linking
        Space"). In the event that one or more Users or any third party initiate
        any type of claim or legal actions against a User or Offering User, each
        and every one of those involved in said claims or actions exempts MASSES
        and its directors, managers, employees, agents, officers,
        representatives and attorneys from all liability.
        <br />
        <br />
        The Linking Space is limited to the provision of a technology platform
        that allows the Users of the Mobile Application and the Site, to link
        immediately with Users from all over the world and thus be able to meet
        the needs of one with the UGC of the other.
        <br />
        <br />
        The User knows and accepts that when carrying out operations with other
        Users or third parties, they do so at their own risk and that they will
        make an evaluation of the risks incurred when hiring an Offering User,
        keeping due proportion between the risk and the selected means.
        <br />
        <br />
        This agreement does not create any partnership, mandate, franchise, or
        employment relationship between MASSES and the Users. The Users
        acknowledge and accept that MASSES is not a party to any operation, nor
        does it have any control over the quality, security or legality of the
        UGC or advertisements, the veracity or accuracy of the advertisements,
        the Users' ability to provide such content or to pay for them.
        <br />
        <br />
        The T&Cs as well as the Privacy Policies and/or information about the
        Mobile Application and the Site apply to all Users of the Mobile
        Application and the Site from the first moment they enter it. These T&Cs
        are mandatory and binding and apply to all activities carried out on the
        Mobile Application and the Site. If Users do not fully accept these
        T&Cs, and the Privacy Policies and other legal notices of the Site, they
        shall not use the Mobile Application and the Site.
        <br />
        <br />
        The User and Offering User are responsible for ensuring that all persons
        who access the Mobile Application and the Site through their Internet
        connection are aware of the T&Cs and that they comply with them.
        <br />
        <br />
        <h3 className="terms-titles">
          Declaration of Offering Users and Users:
        </h3>
        The Offering User declares, understands and declares:
        <ul className="a" style={{ listStyleType: "circle" }}>
          <li>
            That he/she is not carrying out any performance and interpretation
            through the UGC, he/she states that he/she is not an actor/actress,
            and that the UGC sent through the MASSES Web and Mobile Application
            must not contain any performance, nor are they scripted.
          </li>
          <li>
            And he/she guarantees that the UGC uploaded and made available on
            the Mobile Application and the Site, do not contain any pre-existing
            and/or infringing material, as well as he/she guarantees and
            declares to have obtained all the pertinent authorizations to the
            UGC, which allow the peaceful use thereof.
          </li>
          <li>
            He/she declares that his/her UGC is of a purely testimonial nature
            and not theatrical, and any specific legislation related to actors
            shall not be applicable to the relationship between the parties.
          </li>
          <li>
            He/she expressly declares that he/she is not a member of SAG-AFTRA,
            and that you do not have the right to be one by virtue of the UGC
            uploaded and offered through the Mobile Application and the Site.
          </li>
        </ul>
        <br />
        MASSES accepts and receives said declaration and states that it is not a
        film production company, but a mere technical intermediary, which
        through its Technological Platform (hereinafter the "Platform") allows
        the Users of the Mobile Application and the Site, to link in an
        immediate way being able to bring the UGC created by the Offering Users
        to the User. The Users declare that said intervention and/or link
        through the technological platform shall not constitute any type of
        employment relationship with MASSES for the Offering User and the User.
        <br />
        <br />
        <h3 className="terms-titles">You must know:</h3>
        Before each contract, as User and Offering User, you will have to read,
        understand and accept all the conditions established in the T&Cs and in
        the Policies of MASSES. If you use the Mobile Application and the Site,
        it means that you have fully accepted the conditions established in the
        T&Cs and in the MASSES Policies. We shall have the right to suspend or
        delete certain User accounts that by action or omission commit a
        violation of these T&Cs.
        <br />
        <br />
        Once you have registered as Offering User you will periodically receive
        notifications through the App and/or you may eventually receive emails
        and/or any other method for your convenience, with the information from
        the Mobile Application and the Site and the calls that are related to
        your profile. If you do not want to receive more emails, you must
        indicate it by clicking on the corresponding box in "My account" or
        through the email that we have sent you in the option that appears at
        the end of it.
        <br />
        <br />
        <h3 className="terms-titles">When you register as a MASSES User:</h3>
        It is mandatory that you complete all the fields of the registration
        form with valid data in order to start participating in the calls of The
        Mobile Application and the Site. You must complete it with the personal
        information in an exact, precise and true way ("Personal Data")
        undertaking the commitment to update the Personal Data as necessary.
        <br />
        <br />
        As Users, you must guarantee and respond, in any case, to the
        truthfulness, accuracy, validity and authenticity of the Personal Data
        entered. entered.
        <br />
        <br />
        MASSES may use various means to identify its Users, but MASSES is not
        responsible for the accuracy of the Personal Data provided by its Users.
        <br />
        <br />
        MASSES has the right to request some proof and/or additional data in
        order to confirm the Personal Data, as well as to temporarily or
        permanently suspend those Users whose data could not be confirmed. In
        cases of disqualification, they shall be removed from possible future
        calls, without generating any right to compensation.
        <br />
        <br />
        MASSES has the right to reject any application for registration or
        cancel a registration previously accepted, without being compelled to
        communicate or state the reasons for its decision and without generating
        any right to compensation or indemnification.
        <br />
        <br />
        Remember that by submitting the UGC you are granting us and our
        affiliates a perpetual, irrevocable, worldwide, non-exclusive,
        royalty-free and fully sublicensable right and a license to use,
        reproduce, modify, adapt, publish, translate, distribute, perform and
        show said UGC, always by virtue of the purposes proposed for each call.
        If in the UGC you have included personal data about another person,
        before sending it, you must ensure and guarantee that said person has
        consented to be bound by these T&Cs.
        <br />
        <br />
        As User and Offering User, you accept and understand that MASSES can
        keep your content for as long as it needs to complete the purposes for
        which it was collected. If the call has ended and after the selection
        process your UGC has not been chosen by the User, we will proceed to
        fully destroy what you have sent us by virtue of said call.
        <br />
        <br />
        If your UGC has been selected, the rights and terms thereof shall be
        subject to what is established and specified in the contract that you
        subsequently enter into through our platform.
        <br />
        <br />
        <h3 className="terms-titles">
          UGC rules, that is, all content uploaded, sent and chosen:
        </h3>
        You have to know that as Offering User you are accepting and
        guaranteeing that the UGC sent does not contain:
        <ul className="a" style={{ listStyleType: "circle" }}>
          <li>Material that is Defamatory for anyone</li>
          <li>Any obscene, offensive, defamatory material</li>
          <li>Any sexually explicit material</li>
          <li>Any material that promotes violence</li>
          <li>
            Any material that promotes discrimination based on race, sex,
            religion, national origin, disability, sexual orientation or age
          </li>
          <li>
            Any copyright, database right, or trademark of any other person
          </li>
          <li>The privacy rights of any other person</li>
          <li>
            The personal data of another person, unless you ensure that said
            person has consented to be bound by these T&amp;amp;Cs
          </li>
          <li>Any material that promotes any illegal activity</li>
          <li>Threats, abuse, or invasion of another person's privacy</li>
          <li>
            Content that causes unnecessary inconvenience, inconvenience, or
            anxiety
          </li>
          <li>
            Harassment, upsets, or content that embarrasses, alarms, or upsets
            any other person
          </li>
          <li>Content by which you violate the identity of another person</li>
        </ul>
        The Offering User expressly declares and guarantees that the UGC does
        not contain any pre-existing or infringing material and that it has
        obtained the corresponding authorizations to allow the peaceful use of
        the UGC.
        <br />
        <br />
        Any UGC that you upload to the Mobile Application and the Site will be
        considered non-confidential and MASSES has the right to use, copy and
        disclose said content to third parties for the purposes of the Call.
        MASSES has the right to reveal the identity of the same to any third
        party who claims that any content sent constitutes a violation of their
        intellectual property rights, or their right to privacy.
        <br />
        <br />
        MASSES will not be liable to third parties for the UGC or the accuracy
        of any sent UGC. MASSES has the right to remove any UGC or advertisement
        sent through the Mobile Application and the Site at its sole discretion.
        <br />
        <br />
        <h3 className="terms-titles">Your password key:</h3>
        As Users, you are responsible for the confidentiality and use of your
        password keys and all the information that you enter in the Mobile
        Application and the Site.
        <br />
        <br />
        Remember that as Users only you are authorized to your own accounts and
        therefore you should not reveal your passwords to anyone else. If you
        discover that someone unauthorized is using your account, please contact
        us immediately.
        <br />
        <br />
        <h3 className="terms-titles">Operating through MASSES:</h3>
        You must also understand and accept that all the risks and consequences
        involved in the operations carried out through the Mobile Application
        and the Site shall be your sole responsibility, exempting MASSES from
        any type of responsibility that may be incurred during the operation of
        the Mobile Application and the Site.
        <br />
        <br />
        MASSES may modify the structure of the Mobile Application and the Site
        as well as the mechanism by which the instructions are given, notifying
        Users through the mechanisms established in the T&Cs. MASSES shall
        understand that Users have acknowledged of and accepted the
        modifications by continuing to use the Mobile Application and the Site
        and participating in calls.
        <br />
        <br />
        <h3 className="terms-titles">OFFERING Users and Users :</h3>
        <ol className="a" style={{ listStylePosition: "outside" }}>
          <li>
            Any natural person who receives a user account from MASSES in order
            to be able to offer their UGC to other Users on the Mobile
            Application and the Site is recognized as Offering User.
          </li>
          <li>
            Any natural and/or legal person who subscribes and receives from
            MASSES a user account in the Mobile Application and the Site in
            order to contract the UGC uploaded and offered by the Offering Users
            is recognized as User.
          </li>
        </ol>
        <h3 className="terms-titles">
          Legal responsibilities of Offering Users and Users before MASSES :
        </h3>
        <ol className="a" style={{ listStylePosition: "outside" }}>
          <li>
            MASSES is a mere technical intermediary that makes a Technological
            Platform, a digital mechanism, available so that Offering Users can
            offer content generated by themselves, such as videos, audio and/or
            photos, to the community of Users of the Mobile Application and the
            Site.
          </li>
          <li>
            In no case shall MASSES be responsible for damages and/or losses
            and/or losses of any kind that the Offering Users and/or Users may
            suffer as a consequence or on the occasion of the contracting
            between them, nor shall it be responsible for the terms of
            contracting agreed between the Users.
          </li>
          <li>
            MASSES is solely a mere technical intermediary between Users,
            offering a platform that facilitates the meeting between Offering
            Users and Users so that they can be linked, some offering their UGC
            in the Mobile Application and the Site and others being able to buy
            such offers. Likewise, the Offering User, when offering their UGC,
            accepts and acknowledges that MASSES does not have a direct
            relationship with the User, therefore, Users must be aware and
            accept that MASSES is not responsible for any act committed by Users
            and/or by third parties, including but not limited to pre-selected
            UGC withdrawals or cancellation thereof, delays, refusals of
            payments, losses, and others. Users accept that they must have the
            knowledge and that they approve that when using the Mobile
            Application and the Site they must assume the risks that this
            entails under their sole responsibility.
          </li>
        </ol>
        <br />
        <h3 className="terms-titles">Indemnity:</h3>
        The Offering User and the User shall defend, exonerate and hold MASSES
        harmless from all damage, responsibility and cost that may arise as a
        result of a third party claim, action or lawsuit against MASSES and/or
        its directors and/or representatives and/or employees of any position,
        including, but not limited to reasonable legal expenses, resulting from
        any UGC and/or material that they have provided to MASSES through any
        improper use of the virtual linking environment provided by the Platform
        or in violation of these Terms and Conditions. MASSES shall promptly
        notify them of any demand, action or process through the data that they
        themselves have provided at the time of registration on the platform
        that MASSES offers. By accepting these Terms and Conditions, Users
        acknowledge and accept that MASSES has no direct or indirect
        responsibility in relation to the UGC acquired between the Offering
        Users and each User and/or with third parties.
        <br />
        <br />
        <h3 className="terms-titles">Payment:</h3>
        We clarify that the commercial conditions offered in the Mobile
        Application and the Site are for Users. MASSES is a mere technical
        intermediary and therefore does not participate in the effective
        contracting in any way.
        <br />
        <br />
        By requesting and/or participating in a call you shall be giving your
        express consent to the use of PayPal as the available form for the
        payment of the UGC offered. The Users are obliged not to modify the
        cachet offered in the Call.
        <br />
        <br />
        In the event that your video is selected, MASSES shall be the
        Facilitating Agent so that the User can pay for the UGC generated by the
        Offering User. For this, MASSES shall make its own PayPal account
        available to both categories of Users so that these transactions can be
        carried out without any difficulty, thus facilitating the payment link
        between the Offering Users and each User.
        <br />
        <br />
        Consequently, MASSES shall not be responsible for damages and/or losses
        and other losses that may be caused, which will be the sole
        responsibility of the contracting User and/or companies during the
        commercial management of their businesses. The Users are obliged to hold
        MASSES harmless from any third party claim for any payment made or to be
        made by virtue of the use made by the contracting User and/or companies
        of the UGC for the management of their businesses.
        <br />
        <br />
        <h3 className="terms-titles">Liability - Waiver:</h3>
        All information, products, content and other materials in The Mobile
        Application and the Site, accessible from the same, or in third party
        Sites shall be provided "as is" and without warranties or
        representations of any kind, either expressly or implicitly.
        <br />
        <br />
        Users acknowledge, accept and take responsibility for the risks derived
        from the use of the Internet as a means of electronic commerce, in no
        case neither MASSES nor its suppliers shall be responsible for direct,
        indirect, punitive, incidental, special, resulting damages or any other
        other types, including, but not limited to, damages for loss of use,
        data or earnings, arising from or related to the use of the Mobile
        Application and the Site, with the impossibility or delay in being able
        to use The Mobile Application and the Site, or due to the execution of
        orders or the inability to do so, or with any related information,
        software, products or graphics obtained through the Mobile Application
        and the Site, or which have been accessed from any other form related to
        the use of the Mobile Application and the Site. This provision is
        applicable whether the origin of the damage is contractual,
        non-contractual, even if MASSES or any of its suppliers have been
        notified of the possibility of damage.
        <br />
        <br />
        The Users acknowledge and accept that the System used for the operation
        through the Mobile Application and the Site is a sensitive system that
        depends on different resources and that it may suffer crushes, cuts
        and/or interruptions beyond the control of MASSES, and that system
        response can vary due to various factors, including operating volumes
        and system performance. Users assume the risks and damages that said
        operation could generate.
        <br />
        <br />
        <h3 className="terms-titles">Company Name and Address:</h3>
        The business name of the company is MASSES GLOBAL SAS, and it
        establishes its domicile for all questions related to these T&Cs and for
        any eventuality at Av. Dr. Luis Alberto de Herrera 1248, 11300
        Montevideo, Uruguay. (Sinergia WTC).
        <br />
        <br />
        <h3 className="terms-titles">Notifications:</h3>
        All notifications and/or communications that must be made for the use of
        the website under these T&Cs, must be made in writing: (i) To Users: by
        email, to the email account provided by them, or by registered letter,
        to the address declared in the registration form; (ii) to MASSES: to the
        email account: legal@massescontent.com or to its legal address indicated
        in the previous item.
        <br />
        <br />
        <h3 className="terms-titles">Jurisdiction and Applicable Law:</h3>
        These T&Cs are governed without exception and in all their items by the
        laws of Uruguay and shall be interpreted in accordance with them.
        <br />
        <br />
        In the event of any difference, disagreement or conflict derived from
        the interpretation, validity, scope and/or application of these T&C, the
        Users shall communicate with MASSES in a reliable way, sending their
        claim, so that the parties try to reach an agreement.
        <br />
        <br />
        In the event that it is not possible to reach a solution, and to
        guarantee consumers full access to justice, Users may submit their claim
        to the ordinary Courts of Montevideo, Uruguay with competence in the
        matter in the absence of another jurisdiction established by the
        applicable special regulations. In the event that said option is
        cumbersome or economically unfeasible for Users domiciled abroad, the
        parties, at the request of the Users, shall determine by common
        agreement a mutually convenient mechanism to resolve their differences.
        <br />
        <br />
        <h3 className="terms-titles">Terms and Conditions update:</h3>
        MASSES shall have the right to modify the T&Cs at any time and without
        prior notice, serving its updated publication on the Mobile Application
        and the Site as sufficient notification to the Users. Users accept that
        a printed version of these T&Cs and of any communication given
        electronically shall be admissible as full evidence in the judicial or
        administrative proceedings concerning the Mobile Application and the
        Site.
        <br />
        <br />
        <br />
        <br />
        <h1 className="terms-titles">Privacy policy:</h1>
        <h3 className="terms-titles">
          1. Who is responsible for the processing of your data?
        </h3>
        The one responsible for the processing of your personal data is MASSES
        GLOBAL SAS (hereinafter, "MASSES"), with registered office at Av. Dr.
        Luis Alberto de Herrera 1248, 11300 Montevideo, Uruguay (Sinergia WTC).
        <br />
        <br />
        We inform you that the ownership of the Mobile Application and Website
        of{" "}
        <a href="https://www.massescontent.com/">
          https://www.massescontent.com/
        </a>{" "}
        hereinafter, “the Website”), belongs to MASSES. <br />
        <br />
        The access and/or use of the Mobile Application and Website, confers you
        the condition of User (hereinafter, the "User"), and implies the
        acceptance, from said access and/or use, of this Privacy Policy.
        <br />
        <br />
        Users may contact MASSES at the following email address:
        hello@massescontent.com.
        <br />
        <br />
        <h3 className="terms-titles">
          2. Why is MASSES entitled to carry out the data processing?
        </h3>
        MASSES is entitled to process your data in order to be able to carry
        out, as a mere technical intermediary, the link between the Offering
        Users and the Users.
        <br />
        <br />
        MASSES takes the protection of your privacy and personal data very
        seriously. Therefore, your personal information is kept secure and
        handled with the utmost care.
        <br />
        <br />
        This Privacy Policy regulates the access and use of the Mobile
        Application and Website (hereinafter, the "Access and Use of the Site")
        that are available to Users interested in linking to others in the
        Website.
        <br />
        <br />
        <h3 className="terms-titles">
          3. What are the purposes of the processing of your personal data by
          MASSES?
        </h3>
        Your personal data collected by MASSES may be used for the following
        purposes, according to the consent granted in the corresponding
        registration form:
        <br />
        <br />
        {"     "}
        <b class="terms-titles">3.1</b> Linking both categories of Users on the
        Mobile Application and Website.
        <br />
        <br />
        <b class="terms-titles">3.2</b> The sending of commercial communications
        and/or Newsletter by MASSES and on behalf of third parties:
        <br />
        <br />
        If the User has so consented, their personal data may be used to send
        them by letter, telephone, email, SMS/MMS, or by other equivalent
        electronic means of communication, commercial communications or
        information from companies related to those with the sectors of:
        <br />
        <br />
        <b class="terms-titles">Telecommunications:</b> Telecommunications and
        technology products and services.
        <br />
        <br />
        <b class="terms-titles">Marketing or commercial prospecting.</b>
        <br />
        <br />
        <b class="terms-titles">Media and Audiovisual.</b>
        <br />
        <br /> <b class="terms-titles">3.3</b> Transfer of personal data to
        third-party businesses: If the User has consented to this, their data
        may be transferred to companies related to the sectors that are listed
        and detailed in item 3.2.
        <br />
        <br />
        The purpose of the assignment will be to send, by letter, telephone,
        email, SMS/MMS, or by other equivalent electronic means of communication
        by these companies of information and commercial communications that may
        be of interest to you.
        <br />
        <br />
        <h3 className="terms-titles">
          4. Veracity of the data provided by the Users and data of minors
        </h3>
        Users guarantee that the personal data provided are true and they take
        responsibility for communicating to MASSES any modification thereof.
        Users shall respond, in any case, for the veracity of the data provided,
        and MASSES shall reserve the right to exclude from the functions
        provided on the Mobile Application and Website and/or any User who has
        provided false data, without prejudice to other actions applicable by
        Law.
        <br />
        <br />
        <h3 className="terms-titles">5. Conservation of data</h3>
        The personal data provided shall be kept by MASSES as long as the Users
        do not express their willingness to unsubscribe from the Mobile
        Application and Website, this in order to receive information about the
        company's products.
        <br />
        <br />
        <h3 className="terms-titles">
          6. Users' rights in relation to their data
        </h3>
        Users have the right to:
        <ol>
          <li>Access your personal data.</li>
          <li>Request the rectification of inaccurate data.</li>
          <li>Request its deletion.</li>
          <li>Request the limitation of the processing of their data.</li>
          <li>Oppose the processing of their data.</li>
          <li>Request its portability.</li>
          <li>Not be subject to automated individual decisions.</li>
          <li>In addition, Users may exercise their right to be forgotten.</li>
        </ol>
        <br />
        <br />
        Users can exercise all these rights at the following email address
        hello@massescontent.com indicating the reason for their request and
        providing a copy of their ID.
        <br />
        <br />
        Users can also send their request by ordinary mail to the following
        address: MASSES GLOBAL SAS
        <br />
        <br />
        Av. Dr. Luis Alberto de Herrera 1248, 11300 Montevideo, Uruguay
        (Sinergia WTC).
        <br />
        <br />
        Without prejudice to any other administrative remedy or legal action,
        Users shall have the right to file a claim with a Supervisory Authority,
        in particular in the Member State in which they have their habitual
        residence, place of work or place of the alleged infringement, in in
        case they consider that the processing of their personal data is not
        adequate to the regulations, as well as in the case of not being
        satisfied with the exercise of their rights. The supervisory authority
        to which the claim has been submitted will inform the claimant about the
        course and result of the claim.
        <br />
        <br />
        <h3 className="terms-titles">7. Data security</h3>
        The protection of the privacy and personal data of Users is very
        important to MASSES. Therefore, MASSES does everything in its power to
        prevent their data from being used improperly, allowing access to it
        only to authorized personnel.
        <br />
        <br />
        MASSES maintains the security levels of protection of personal data in
        accordance with the applicable regulations and has established all the
        technical means at its disposal to prevent the loss, misuse, alteration,
        unauthorized access and theft of the data that Users provide through the
        Mobile Application and Website without prejudice to informing you that
        the security measures on the Internet are not impregnable.
        <br />
        <br />
        MASSES undertakes to comply with the duty of secrecy and confidentiality
        regarding personal data in accordance with the applicable legislation,
        as well as to grant them a secure processing in the international
        transfers and assignments of data that, where appropriate, may occur.
        <br />
        <br />
        To register as Offering User and/or User of the Mobile Application and
        Website, they must choose a password. Users are responsible for
        maintaining the confidentiality of this password, as well as all the
        activities that occur in the session started with their name and
        password.
        <br />
        <br />
        Users undertake to notify MASSES as soon as possible of the unauthorized
        use of their Username and/or password or any other security failure.
        MASSES shall not be responsible for the damages or losses that could
        originate due to the non-fulfillment of this obligation by the User.
        <br />
        <h3 className="terms-titles">8. Changes</h3>MASSES reserves the right to
        review its Privacy Policy at the time it deems appropriate. For this
        reason, we ask that you regularly check this Privacy Policy to read the
        most recent version of it. However, any change that occurs in this
        Privacy Policy will be communicated to the User.
        <br />
        <br />
        <h3 className="terms-titles">9. Links to web pages</h3>The MASSES Mobile
        Application and Website may contain links to the websites of third party
        companies and entities. MASSES cannot be held responsible for the way in
        which these companies treat the protection of privacy and personal data,
        so we advise you to carefully read the Privacy Policy statements of
        these web pages that are not owned by MASSES regarding the use,
        processing and protection of personal data.
        <br />
        <br />
        The conditions offered by these web pages may not be the same as those
        offered by MASSES.
        <br />
        <br /> <h3 className="terms-titles">10. Questions</h3>If you have any
        questions about this Privacy Policy or the processing of your data,
        please contact MASSES by email at the following email address:
        hello@massescontent.com.
        <br />
        <br />
        <h3 className="terms-titles">11. Acceptance and Consent</h3>Users
        declare to have been informed of the conditions on protection of
        personal data, accepting and consenting to the treatment thereof by
        MASSES, in the manner and for the purposes indicated in this Privacy
        Policy.
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <div className="terms-bottom">
          {read ? (
            <></>
          ) : (
            <button onClick={() => apr()}>
              I accept the Terms and Conditions and Privacy Policy
            </button>
          )}
        </div>
      </div>
    </div>
  );
};
